### ISSUE TITLE
ROS2 Foxy

### ISSUE THREAD

**Issue by alexMarFar** [ros2/pybind11_vendor#18]
Hi! I'm migrating a project that works with ROS2 Foxy from ROS1 Noetic and it depended on pybind11_catkin, in particular it called headers pybind11/embed and pybind11/eigen.

I was told that pybind11 is directly vendored for ros2 but I am getting some compiling errors:

fatal error: pybind11_vendor/pybind11/embed.hpp: No such file or directory
   16 | #include <pybind11_vendor/pybind11/embed.hpp> // everything needed for embedding // ROS2 updated

Could you please let me know what I did wrong?

Thank you in advance,

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
