### ISSUE TITLE
pybind11_add_module not found

### ISSUE THREAD

**Issue by MaximilienNaveau** [ros2/pybind11_vendor#4]
Dear authors,

I really like the way this is package, it's simple and efficient. :+1: 
Though I encountered a slight issue using it.

I did a `find_package(pybind11_vendor REQUIRED)` in my CMakeLists.txt and therefore (if my understanding of modern CMake + ament is correct), I should be able to simply use the macros `pybind11_add_module`.

Though colcon say something like:
```
CMake Error at CMakeLists.txt:117 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".
```

Can you help me with this?
Do I need to manage to include the `workspace/install/cmake/pybind11/pybind11Tools.cmake` somehow?

Thank you very much for your help!

**Comment by clalancette** [comment]
> I did a `find_package(pybind11_vendor REQUIRED)` in my CMakeLists.txt and therefore (if my understanding of modern CMake + ament is correct), I should be able to simply use the macros `pybind11_add_module`.

It's not enough to just `find_package(pybind11_vendor REQUIRED)`; that only makes the cmake stuff available.  You also need to `find_package(pybind11 REQUIRED)` to get access to the CMake macros.

**Comment by MaximilienNaveau** [comment]
Thank for your very quick reply!
I also tryed to simply do a `find_package(pybind11 REQUIRED)` and it found all that I need.
I guess it worked because pybind11_vendor was install already... WDYT?

In any case I must then do:
```
find_package(pybind11_vendor REQUIRED)
find_package(pybind11 REQUIRED)
```
In my CMakeLists.txt?

Thanks again a lot for the vendor!!!!
