### ISSUE TITLE
Update to pybind11 2.6.0 when it is released

### ISSUE THREAD

**Issue by asobhy-qnx** [ros2/pybind11_vendor#6]
https://github.com/pybind/pybind11/issues/2568

**Comment by asobhy-qnx** [comment]
fix will be in version 2.6 https://github.com/pybind/pybind11/milestone/8

**Comment by asobhy-qnx** [comment]
currently building independently for QNX and patching it before build

**Comment by asobhy-qnx** [comment]
@dirk-thomas

**Comment by sloretz** [comment]
@asobhy-qnx is the ask here to bump the vendored version of pybind11 to 2.6.0 when it releases?

**Comment by jacobperron** [comment]
@sloretz In any case, I would like to bump to 2.6.0 when it is available for an unrelated patch. It will let us revert https://github.com/ros2/rosbag2/pull/538.

**Comment by asobhy-qnx** [comment]
@sloretz yes if it will not be an issue, thank you.

**Comment by jacobperron** [comment]
2.6.0 is released :tada: https://github.com/pybind/pybind11/releases/tag/v2.6.0

**Comment by jacobperron** [comment]
I can look into updating the version for the vendor package.

**Comment by jacobperron** [comment]
See https://github.com/ros2/pybind11_vendor/pull/8

**Comment by asobhy-qnx** [comment]
Nice! Thank you I will test a build too

**Comment by jacobperron** [comment]
We're using pybind11 v2.7.1 sine #10
